CREATE TABLE TASK (
    ID_TASK INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(200) NOT NULL,
    DEADLINE TIMESTAMP NOT NULL,
    PRIORITY INTEGER NOT NULL,
    DONE BOOLEAN NOT NULL,
    PRIMARY KEY (ID_TASK)
)